### ISSUE TITLE
iso-2 Contact name and Contact email issues

### ISSUE THREAD

**Issue by emiliom** [WCGA/West-Coast-Ocean-Data-Portal#27] opened 2015-01-09 00:02 UTC
I've checked the exposed attributes for iso-2 records (at least NANOOS ones). All are ok, except for a couple of issues under "Contact". I went through the XPaths in Metadata.js:
- XPath for _contactName_ should end with "gco\:CharacterString" (and a corresponding "CharacterString" for the substring w/o namespaces). The outcome on the portal client looks fine, though, so this is probably handled correctly despite that small XPath error.
- Contact email (_contactEmail_) is not showing as it should, but it's very puzzling. You'll see easily that the 4 NANOOS iso-2 records have (correctly) "Craig Risien" as contact name, but "bob.simons@noaa.gov" as contact email (obviously not Craig). I examined the XPaths on one of these records, vs _all.js_ on staging. The XPath on all.js is correct. But what appears on the UI does not match the content of that XPath on the metadata xml (which is the correct email corresponding to Craig)! Bizarre. It's as if the client code is not actually getting the email string from _contactEmail_, but from somewhere else in the metadata record.

To explore the second issue a bit further, I took a quick look at one CeNCOOS iso-2 record. I can't make the same email assessment there. But I discovered that it actually has **two** _gmd:CI_ResponsibleParty_ elements! I don't know how the UI code decides between the two, but it looks like the second one was selected for contact name (contact email is identical in the two elements). Sigh.

**Comment by tchaddad** [comment] 2015-02-26 00:27
I've just assigned this one to myself, so I can take a look at it tomorrow...

**Comment by tchaddad** [comment] 2015-05-27 17:25
@twelch by any chance is this issue related to any of the stuff you have been working on?

**Comment by twelch** [comment] 2015-06-12 17:31
@tchaddad yes looks like it may be related to #136 and have a similar solution.  I can look into

**Comment by twelch** [comment] 2015-06-12 17:32
Err this issue attached to the other repo - https://github.com/Ecotrust/wc-data-registry/issues/136

**Comment by emiliom** [comment] 2015-06-17 03:41
Cool! And good to learn that @twelch is "now" looking directly at WCODP innards. I say "now", with awareness that I've been out of the WCODP loop (I think) for the last few months. Hi Tim and Tanya:)

**Comment by twelch** [comment] 2015-07-26 07:56
Turns out it it was matching on the less specific iso selector and was never getting to the isoii selector.  I simply switched them.  

Unfortunately the wcodp code is still maintained in the ecotrust repo so you won't get notifications of commits here.  I just made a pull request for this.  https://github.com/Ecotrust/wc-data-registry/pull/143.  Look forward to reviewing @fishytodd

**Comment by emiliom** [comment] 2015-07-26 18:30
Awesome!

**Comment by twelch** [comment] 2015-08-12 03:16
Simple unit test created to ensure proper values are pulled and any regressions are caught early, more to come, should be reviewed this week - https://github.com/Ecotrust/wc-data-registry/pull/144

**Closed as completed** 2015-09-23 23:29 UTC
Labels: bug, IT Group, P97, Closable, SoundGIS, UI
